version: "3.9"

services:
  web-admin:
    build:
      context: ./apps/web-admin
      dockerfile: Dockerfile
    container_name: dolucrm-web-admin
    env_file:
      - ./apps/web-admin/.env
    depends_on:
      - api
    networks:
      - avara-network
    restart: unless-stopped
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dolucrm-web-admin.rule=Host(`crm.dolugo.com`)"
      - "traefik.http.routers.dolucrm-web-admin.entrypoints=websecure"
      - "traefik.http.routers.dolucrm-web-admin.tls=true"
      - "traefik.http.routers.dolucrm-web-admin.tls.certresolver=letsencrypt"
      - "traefik.http.services.dolucrm-web-admin.loadbalancer.server.port=3000"

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: dolucrm-api
    command: >
      sh -c "npx prisma migrate deploy && node dist/main"
    env_file:
      - ./apps/api/.env
    depends_on:
      - db
    networks:
      - avara-network
    restart: always
    expose:
      - "5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dolucrm-api.rule=Host(`crm-api.dolugo.com`)"
      - "traefik.http.routers.dolucrm-api.entrypoints=websecure"
      - "traefik.http.routers.dolucrm-api.tls=true"
      - "traefik.http.routers.dolucrm-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.dolucrm-api.loadbalancer.server.port=5000"

  db:
    image: postgres:16-alpine
    container_name: dolucrm-db
    env_file:
      - ./apps/api/.env
    ports:
      - "5433:5432"
    volumes:
      - dolucrm-db:/var/lib/postgresql/data
    networks:
      - avara-network
    restart: unless-stopped

volumes:
  dolucrm-db:

networks:
  avara-network:
    name: avara-network
    external: true
    driver: bridge
