export enum exceptionCodes {
  EMAIL_ALREADY_EXISTS_EXCEPTION = 'EMAIL_ALREADY_EXISTS_EXCEPTION',
  USER_NOT_FOUND_EXCEPTION = 'USER_NOT_FOUND_EXCEPTION',
  INVALID_CREDENTIALS_EXCEPTION = 'INVALID_CREDENTIALS_EXCEPTION',
  COMPANY_NOT_FOUND_EXCEPTION = 'COMPANY_NOT_FOUND_EXCEPTION',
  MISSING_TOKEN_CLAIM_EXCEPTION = 'MISSING_TOKEN_CLAIM_EXCEPTION',
  COMPANY_NOTE_NOT_FOUND_EXCEPTION = 'COMPANY_NOTE_NOT_FOUND_EXCEPTION',
  ACCESS_DENIED_EXCEPTION = 'ACCESS_DENIED_EXCEPTION',
  ATTRIBUTE_TYPE_NOT_FOUND_EXCEPTION = 'ATTRIBUTE_TYPE_NOT_FOUND_EXCEPTION',
  ATTRIBUTE_TYPE_HAS_VALUES_EXCEPTION = 'ATTRIBUTE_TYPE_HAS_VALUES_EXCEPTION',
  ATTRIBUTE_TYPE_ALREADY_EXISTS_EXCEPTION = 'ATTRIBUTE_TYPE_ALREADY_EXISTS_EXCEPTION',
}
